reduce:
  tables:
    sales_order:
      column: created_at
      statement: < DATE_SUB(NOW(),INTERVAL 1 YEAR)
    sales_order_grid:
      column: created_at
      statement: < DATE_SUB(NOW(),INTERVAL 1 YEAR)
    sales_invoice:
      column: created_at
      statement: < DATE_SUB(NOW(),INTERVAL 1 YEAR)
    sales_creditmemo:
      column: created_at
      statement: < DATE_SUB(NOW(),INTERVAL 1 YEAR)
    sales_shipment:
      column: created_at
      statement: < DATE_SUB(NOW(),INTERVAL 1 YEAR)
    quote:
      column: created_at
      statement: < DATE_SUB(NOW(),INTERVAL 1 YEAR)
    customer_entity:
      column: created_at
      statement: < DATE_SUB(NOW(),INTERVAL 1 YEAR)